### ISSUE TITLE
Tune down issue notifications

### ISSUE THREAD

**Issue by pitrou** [apache/arrow-nanoarrow#27]
Currently, every comment on every PR and issue is forwarded to the Arrow issues ML. It would be to tune that down to perhaps just sending notifications of issue and PR creations.

**Comment by paleolimbot** [comment]
I have no idea why that happens or how to stop it!

**Comment by wesm** [comment]
Here's Arrow's .asf.yaml

https://github.com/apache/arrow/blob/master/.asf.yaml

and this repo's

https://github.com/apache/arrow-nanoarrow/blob/main/.asf.yaml

I suggest copying over the the e-mail settings from the main Arrow repository

**Comment by wesm** [comment]
```
notifications:
  commits:      commits@arrow.apache.org
  issues:       github@arrow.apache.org
  pullrequests: github@arrow.apache.org
```

**Comment by kou** [comment]
FYI: apache/arrow-julia uses the following configuration to send only issue open/close notifications to issues@ (issue comments and pull request related notifications aren't sent):

https://github.com/apache/arrow-julia/blob/main/.asf.yaml

```yaml
notifications:
  commits: commits@arrow.apache.org
  issues: issues@arrow.apache.org
  issues_comment: github@arrow.apache.org
  pullrequests: github@arrow.apache.org
```
